### ISSUE TITLE
Feature: Add a swagger UI for admin api

### ISSUE THREAD

**Issue by pmiossec** [WireMock-Net/WireMock.Net#268]
To make the use of the admin api easier, it could be interesting to add swagger UI.

See https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-2.2 and https://swagger.io/tools/swagger-ui/

**Comment by StefH** [comment]
I know. But adding automatically generated swagger to this wep-api is not possible because also the admin interface is dynamically defined.

Some time ago I did start a Swagger Doc here:
https://app.swaggerhub.com/apis/StefHeyenrath/WireMock/1.0.13.0

However, I think not all data is here yet.
So feel free to update ;-)

(And I will also take a look if I can add some more commands ....)

**Comment by pmiossec** [comment]
>But adding automatically generated swagger to this wep-api is not possible because also the admin interface is dynamically defined.

Ok, that was the reason.... I understand better now.

I just didn't know if you knew it (even if I found it surprising) and that's just after I created the issue that I saw the swaggerhub link). And I didn't found an issue talking about it. So I hope this issue will serve as a doc.

Swaggerhub is better than nothing but I find it clearly less usable than the embedded swagger UI (I didn't found how to specify the host when you run wiremock on other port than 80). 

>So feel free to update ;-)

I will be pleased to do it if I see something missing and if I will use wiremock more than just what I do for now. But don't expect a lot ;) We will see.

Thanks a lot for your clear answer.
