### ISSUE TITLE
Intermittent threading errors with FindLogEntries

### ISSUE THREAD

**Issue by davidpene** [WireMock-Net/WireMock.Net#408]
When running tests in parallel, we intermittently get this exception:
``` c#
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at WireMock.Server.FluentMockServer.FindLogEntries(IRequestMatcher[] matchers) in /Server/FluentMockServer.LogEntries.cs:line 42
```

**Comment by NoahLerner** [comment]
I'm trying to understand the root cause of this issue but could use some more information.
Are you running tests in parallel using the same `WireMockServer` instance? Or does each test create a new instance?

Additionally,    
```csharp
at WireMock.Server.FluentMockServer.FindLogEntries(IRequestMatcher[] matchers) in /Server/FluentMockServer.LogEntries.cs:line 42
```
does not point to a line of code in my version of the repo. Are you running the latest nuget package?

**Comment by davidpene** [comment]
We're running tests in parallel and using a static wiremock server to mock a single "api". We're using version `1.0.7`. I'll bump to the latest `1.1.9.0` and let you know if the issue continues.

**Comment by NoahLerner** [comment]
Hey David, did updating the nuget package resolve your issue?

**Comment by davidpene** [comment]
Hey @NoahLerner the issue was intermittent and it hasn't shown up again, so it _may_ have been solved. Happy to close this issue and I'll reopen if I see it again.
Cheers
