### ISSUE TITLE
Consistent API for defining expectations.

### ISSUE THREAD

**Issue by cezarypiatekGC** [WireMock-Net/WireMock.Net#503]
Hi, 

I would like to use WireMock.Net in my project but I need to handle the following scenario. When we run tests locally (in VisualStudio) then we want to run WireMock in memory using WireMockServer.Start. When we run tests in CI then we want to use docker container with WireMock and connect to it from the test code and from the tested application. Besides that difference, we would like to have a consistent API to define mocking rules. However, it doesn't seem to be possible right now because WireMock client uses different models to define mappings (MappingModel) and the MappingConverter which could convert IMapping to MappingModel has an internal modifier. Is it possible to expose the method which could perform that conversion? Or am I doing something wrong and there's an option to define Mappings once and use it with WireMockServer and with standalone (docker) app? Ofc, WireMockServer has WithMapping method which accepts MappingModel but creating MappingModel manually seems to be a very tedious task. I Would prefer to use that fluent interface with Request.Create() and Response.Create()

**Comment by StefH** [comment]
Hello @cezarypiatekGC,

For your scenario I would recommend to use (static) mapping files to be used in your local unit-tests and by your WireMock.net running in a docker container.

## 1. Create a mapping.json file
For the format, see https://github.com/WireMock-Net/WireMock.Net/wiki/Admin-API-Reference#post---__adminmappings

And place this file in the **__admin/mappings** folder.

## 2. Now in your unit tests, you can use:
``` c#
var server = WireMockServer.Start(new WireMockServerSettings
{
  ReadStaticMappings = true,
  WatchStaticMappings = true,
  WatchStaticMappingsInSubdirectories = true
};
``` 

The unit tests will use the mappings defined in the mapping.json file.

See also https://github.com/WireMock-Net/WireMock.Net/wiki/Settings#readstaticmappings


## 3. Docker

Getting this to work in docker container is not 100% easy supported because loading that mapping.json file can not be done at startup because the docker image is already created.

Some options what you could do is after the docker container has been started, just use the admin rest interface to post the mapping.json content.
You can just use any tool to do a http post to the /__admin endpoint, or use the c# client api:
https://github.com/WireMock-Net/WireMock.Net/wiki/Admin-API-Reference#client-api

**Comment by StefH** [comment]
Or, you can also just run a console app instead of a docker image. See https://github.com/HeadsInsane/Challenge/tree/master/src/BankSimulator and the related main project on how it's also possible.

**Comment by cezarypiatekGC** [comment]
Hi @StefH 
Thanks for your response. Is there any reason that prevents you from exposing `MappingConverter`? That would simply a lot.

**Comment by StefH** [comment]
There is no real reason, except that I'd like to expose only the classes which are really used by the users.

But if it helps you, I can make this class public. And add a comment like `This class is used by WireMock.Net internally. It isn't intended for use in application code.`

**Comment by StefH** [comment]
@cezarypiatekGC What do you think of my previous answer?

**Comment by cezarypiatekGC** [comment]
I started using `WithMapping` method to define mocks (and created my own abstraction over this tedious API), but there are some discrepancies in the final behavior of those two API's, the problem is reported here https://github.com/WireMock-Net/WireMock.Net/issues/504

**Comment by StefH** [comment]
Hello @cezarypiatekGC,

If you want to test a preview fix for this issue, in order to test that you need MyGet version `WireMock.Net.1.2.18-ci-13754.nupkg`.

Can you test if that one does work correct?

**Comment by StefH** [comment]
@cezarypiatekGC 
I close this issue.

In case you still have questions, just create a new issue.
