### ISSUE TITLE
Is this compatible with WireMock?

### ISSUE THREAD

**Issue by bfrggit** [WireMock-Net/WireMock.Net#727]
Is this compatible with WireMock (https://wiremock.org/)? Briefly, I just replaced my Docker Compose's ref to the latter's image to this image and it does not pick up the mapping files I mounted to container.

My team has a cluster that uses this (WireMock.Net), however my service is Java and was using WireMock (org) and its Java SDK. If this is not compatible, does this have a Java SDK?

**Comment by StefH** [comment]
Hello @bfrggit,

There is some limited support for the mapping from WireMock.org

See also these links:
- https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock.Org
- #491

However it could be that your mapping does not work yet.

Please post the full mapping file here.

**Comment by bfrggit** [comment]
@StefH The examples you show in the links look promising. However, before testing with the actual payload, we'd like to know if the following features are there or if WireMock.Net plans to stay consistent with WireMock.org -- 

- Auto loading mapping stubs from filesystem and using JSON files as response body. Also, if the directory structure of these are consistent with that of WireMock.org.
- Java SDK, or if it is compatible with the WireMock.org Java SDK, which means the APIs must be consistent.
- Global response templating, so we can have template fields in the JSON file used for responses.
- Multi-stubbing (e.g., general vs. case-specific).

**Comment by bfrggit** [comment]
No longer urgent since we got a green light to also deploy WireMock.org in test cluster.

**Comment by StefH** [comment]
If you still have time, can you please provide a mapping which you use now for wiremock.org ?
So that I can check if this works and fix the code from wiremock.net to also support that mapping.

**Comment by bfrggit** [comment]
@StefH The truth is that it may or may not be related to mapping itself... Could be just location of the files but I did not spend much time digging into it. I will quickly check it today.

**Comment by bfrggit** [comment]
@StefH However, we'd still like to know if the following features are supported or on the roadmap --

- Auto loading mapping stubs from filesystem and using JSON files as response body. Also, if the directory structure of these are consistent with that of WireMock.org.
- Java SDK, or if it is compatible with the WireMock.org Java SDK, which means the APIs must be consistent.
- Global response templating, so we can have template fields in the JSON file used for responses.
- Multi-stubbing (e.g., general vs. case-specific).

And also, is WireMock.Net supposed to stay consistent with WireMock.org?

**Comment by bfrggit** [comment]
First of all, according to https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching, the JSON payload seems to use UpperCamelCase for property naming but I think WireMock.org uses snake_case?

**Comment by bfrggit** [comment]
Well I tried today but could not figure out where I should put the `mappings` folder and `__files` folder in the container (Linux) to let it pick them up automatically. Will stop trying until I hear from you about the features above.

**Comment by StefH** [comment]
## Should work / same
- Auto loading mapping stubs from filesystem and using JSON files as response body. 
- Also, if the directory structure of these are consistent with that of WireMock.org.
- Global response templating, so we can have template fields in the JSON file used for responses. --> https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating
- Multi-stubbing (e.g., general vs. case-specific). --> https://github.com/WireMock-Net/WireMock.Net/wiki/Scenarios-and-States
- the JSON payload seems to use UpperCamelCase for property naming but I think WireMock.org uses lowerCamelCase? (I think the json deserialzier from .NET can handle both)


## Not 100% compatible and no plans to keep it compatible because Java and C# are different
- Java SDK, or if it is compatible with the WireMock.org Java SDK, which means the APIs must be consistent.
- And also, is WireMock.Net supposed to stay consistent with WireMock.org?


- Well I tried today but could not figure out where I should put the mappings folder and __files folder in the container (Linux) to let it pick them up automatically. Will stop trying until I hear from you about the features above.
--> https://github.com/WireMock-Net/WireMock.Net-docker/wiki/Docker-Compose


I hope this answers your questions.
